stages:
  - deploy

image: node:14

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_REGISTRY_TOKEN}" > .npmrc
  - npm ci --cache .npm --prefer-offline

cache:
  key: "react-native-modpow" # universal cache
  paths:
    - .npm/

deploy:
  stage: deploy
  script:
    - if (npx semver $CI_COMMIT_TAG --range '>0.0.0'); then NPM_TAG=latest; else NPM_TAG=beta; fi; # Using the fact that semver by default considers that pre-releases do not respect stable ranges
    - npm publish --tag=$NPM_TAG
  only:
    - tags
